-- criação da tabela market

create table public.market (
   id_market int8 generated by default as identity,
   created_at timestamp not null,
   price int4 not null,
   id_skill int8 not null,
   primary key (id_market)
)

-- criação da tabela skill

create table public.skill (
   id_skill int8 generated by default as identity,
   description varchar(255) not null,
   imageurl varchar(255) not null,
   is_market boolean not null,
   level int4 not null,
   name varchar(255) not null,
   id_user int8 not null,
   primary key (id_skill)
) 

-- criação da tabela user

create table public.user (
   id_user int8 generated by default as identity,
   coins int4 not null,
   created_at timestamp not null,
   email varchar(255) not null,
   password varchar(255) not null,
   perfil int4 not null,
   user_name varchar(255) not null,
   primary key (id_user)
)

-- criação das constraints

alter table
   if exists public.market
add
   constraint FKnvrubw0njwybxs7mg3i6o7wu4 foreign key (id_skill) references public.skill

alter table
   if exists public.skill
add
   constraint FKl1tj78tofr3ep4uagdoqrvq64 foreign key (id_user) references public.user